name: Distscraper

on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: npm ci
      env:
        CI: true
    - name: run aws s3 cp
    - run: aws s3 cp s3://drivedroid-repositories/all.json ./
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-1'
    - name: Run
      run: |
        mkdir -p out
        cd out
        node ../index.js --merge ../all.json --directory ../scrapers
        cd -
    - run: aws s3 sync out/ s3://drivedroid-repositories/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-1'
